package com.hamdard.hua.privileges;

public enum Privilege {
    ACCOUNT_ALL_READ_CMD,
    ACCOUNT_UPDATE_CMD,
    ACCOUNT_DELETE_CMD,
    ACCOUNT_CREATE_CMD,
    COLLEGE_ALL_READ_CMD,
    DEPARTMENT_ALL_READ_CMD,
    DESIGNATION_ALL_READ_CMD,
    COUNTRY_ALL_READ_CMD,
    UNIT_ALL_READ_CMD,
    DISTRICT_ALL_READ_CMD,
    DEFAULT
}
