CREATE USER HUAAPPUSER IDENTIFIED BY 'HUAAPPUSER';
CREATE DATABASE HUA;
USE HUA;
GRANT ALL ON HUA TO HUAAPPUSER;

CREATE SEQUENCE ACCESS_ID START WITH 1 INCREMENT BY 1 CACHE 5;

CREATE TABLE ACCESS_TOKEN (
  ACCESS_ID INTEGER,
  INSERT_DTM DATE DEFAULT SYSDATE,
  USER_NAME VARCHAR(30),
  EXPIRY_DTM DATE,
  REFRESH_COUNT INTEGER,
  LAST_REFRESH_DTM DATE
);

CREATE TABLE ACTIVITY_HISTORY (
  INSERT_DTM DATE,
  USER_NAME VARCHAR(30),
  MESSAGE VARCHAR(4000)
);
