INSERT INTO APP_SEQUENCE VALUES ('ACCESS_ID',1);
INSERT INTO APP_SEQUENCE VALUES ('EMPLOYEE_ID',1);

INSERT INTO EMPLOYEE VALUES(1,	'Anne',	NULL,	'Moody',	'Anne.Moody@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(2,	'Winston',	NULL,	'Figueroa',	'Winston.Figueroa@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(3,	'Patti',	NULL,	'Arnold',	'Patti.Arnold@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(4,	'Bertha',	NULL,	'Castro',	'Bertha.Castro@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(5,	'Santos',	NULL,	'Townsend',	'Santos.Townsend@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(6,	'Krystal',	NULL,	'Hodges',	'Krystal.Hodges@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(7,	'Clarence',	NULL,	'Haynes',	'Clarence.Haynes@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(8,	'Allan',	NULL,	'Boyd',	'Allan.Boyd@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(9,	'Ramiro',	NULL,	'Garza',	'Ramiro.Garza@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(10,	'Camille',	NULL,	'Robertson',	'Camille.Robertson@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(11,	'Monique',	NULL,	'Wong',	'Monique.Wong@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(12,	'Alton',	NULL,	'Keller',	'Alton.Keller@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(13,	'Dean',	NULL,	'Lee',	'Dean.Lee@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(14,	'Jeannette',	NULL,	'Rose',	'Jeannette.Rose@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(15,	'Henry',	NULL,	'Myers',	'Henry.Myers@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(16,	'Claudia',	NULL,	'Manning',	'Claudia.Manning@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(17,	'Susan',	NULL,	'Greer',	'Susan.Greer@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(18,	'Ellis',	NULL,	'Thornton',	'Ellis.Thornton@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(19,	'Emanuel',	NULL,	'Sandoval',	'Emanuel.Sandoval@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(20,	'Emilio',	NULL,	'Saunders',	'Emilio.Saunders@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(21,	'Carlos',	NULL,	'Benson',	'Carlos.Benson@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(22,	'Mike',	NULL,	'Parsons',	'Mike.Parsons@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(23,	'Genevieve',	NULL,	'Fox',	'Genevieve.Fox@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(24,	'Bryan',	NULL,	'Copeland',	'Bryan.Copeland@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(25,	'Susie',	NULL,	'Watson',	'Susie.Watson@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(26,	'Ernestine',	NULL,	'Pratt',	'Ernestine.Pratt@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(27,	'Jose',	NULL,	'Harris',	'Jose.Harris@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(28,	'Rosemary',	NULL,	'Vaughn',	'Rosemary.Vaughn@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(29,	'Essie',	NULL,	'Tran',	'Essie.Tran@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(30,	'Dixie',	NULL,	'Dixon',	'Dixie.Dixon@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(31,	'Aubrey',	NULL,	'Morgan',	'Aubrey.Morgan@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(32,	'Alberta',	NULL,	'Hansen',	'Alberta.Hansen@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(33,	'Pearl',	NULL,	'Shelton',	'Pearl.Shelton@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(34,	'Jessica',	NULL,	'Gardner',	'Jessica.Gardner@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(35,	'Willie',	NULL,	'Shaw',	'Willie.Shaw@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(36,	'Shelia',	NULL,	'Hale',	'Shelia.Hale@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(37,	'Rolando',	NULL,	'Sims',	'Rolando.Sims@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(38,	'Lori',	NULL,	'Estrada',	'Lori.Estrada@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(39,	'Stacy',	NULL,	'Mitchell',	'Stacy.Mitchell@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(40,	'Kay',	NULL,	'Mann',	'Kay.Mann@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(41,	'Dana',	NULL,	'Stone',	'Dana.Stone@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(42,	'Earnest',	NULL,	'Wilkins',	'Earnest.Wilkins@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(43,	'Phillip',	NULL,	'Cannon',	'Phillip.Cannon@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(44,	'Lorena',	NULL,	'Richards',	'Lorena.Richards@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(45,	'Bobby',	NULL,	'Holloway',	'Bobby.Holloway@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(46,	'Doris',	NULL,	'Quinn',	'Doris.Quinn@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(47,	'Guillermo',	NULL,	'Hammond',	'Guillermo.Hammond@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(48,	'Jack',	NULL,	'Nash',	'Jack.Nash@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(49,	'Sam',	NULL,	'Mathis',	'Sam.Mathis@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(50,	'Silvia',	NULL,	'Torres',	'Silvia.Torres@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(51,	'Travis',	NULL,	'Wade',	'Travis.Wade@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(52,	'Jay',	NULL,	'Bradley',	'Jay.Bradley@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(53,	'Debbie',	NULL,	'Tate',	'Debbie.Tate@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(54,	'Rhonda',	NULL,	'Foster',	'Rhonda.Foster@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(55,	'Lucas',	NULL,	'Olson',	'Lucas.Olson@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(56,	'Alex',	NULL,	'Oliver',	'Alex.Oliver@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(57,	'Jennifer',	NULL,	'Lucas',	'Jennifer.Lucas@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(58,	'Todd',	NULL,	'Chandler',	'Todd.Chandler@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(59,	'Colin',	NULL,	'Clayton',	'Colin.Clayton@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(60,	'Bernard',	NULL,	'Mason',	'Bernard.Mason@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(61,	'Derrick',	NULL,	'Rhodes',	'Derrick.Rhodes@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(62,	'Violet',	NULL,	'Fisher',	'Violet.Fisher@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(63,	'Leon',	NULL,	'Schmidt',	'Leon.Schmidt@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(64,	'Marta',	NULL,	'Cole',	'Marta.Cole@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(65,	'Spencer',	NULL,	'Martinez',	'Spencer.Martinez@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(66,	'Gustavo',	NULL,	'Jackson',	'Gustavo.Jackson@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(67,	'Cassandra',	NULL,	'Colon',	'Cassandra.Colon@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(68,	'Jeanette',	NULL,	'Stevens',	'Jeanette.Stevens@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(69,	'Everett',	NULL,	'Klein',	'Everett.Klein@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(70,	'Alison',	NULL,	'Duncan',	'Alison.Duncan@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(71,	'Aaron',	NULL,	'Wood',	'Aaron.Wood@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(72,	'Angelina',	NULL,	'Nichols',	'Angelina.Nichols@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(73,	'Kristina',	NULL,	'Perry',	'Kristina.Perry@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(74,	'Virginia',	NULL,	'Dean',	'Virginia.Dean@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(75,	'Delbert',	NULL,	'Wagner',	'Delbert.Wagner@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(76,	'Gregory',	NULL,	'Vargas',	'Gregory.Vargas@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(77,	'Irma',	NULL,	'Perkins',	'Irma.Perkins@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(78,	'Christie',	NULL,	'Cohen',	'Christie.Cohen@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(79,	'Tami',	NULL,	'Luna',	'Tami.Luna@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(80,	'Norman',	NULL,	'Hardy',	'Norman.Hardy@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(81,	'Guadalupe',	NULL,	'Erickson',	'Guadalupe.Erickson@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(82,	'Amber',	NULL,	'Kennedy',	'Amber.Kennedy@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(83,	'Henrietta',	NULL,	'Blair',	'Henrietta.Blair@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(84,	'Jeff',	NULL,	'Snyder',	'Jeff.Snyder@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(85,	'Archie',	NULL,	'Mcbride',	'Archie.Mcbride@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(86,	'Thelma',	NULL,	'Jimenez',	'Thelma.Jimenez@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(87,	'Edmund',	NULL,	'Lopez',	'Edmund.Lopez@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(88,	'Kirk',	NULL,	'Berry',	'Kirk.Berry@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(89,	'Mildred',	NULL,	'Chavez',	'Mildred.Chavez@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(90,	'Julio',	NULL,	'Delgado',	'Julio.Delgado@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(91,	'Laverne',	NULL,	'Carter',	'Laverne.Carter@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(92,	'Eloise',	NULL,	'Hicks',	'Eloise.Hicks@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(93,	'Doreen',	NULL,	'Rodriguez',	'Doreen.Rodriguez@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(94,	'Connie',	NULL,	'Gutierrez',	'Connie.Gutierrez@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(95,	'Marvin',	NULL,	'Baker',	'Marvin.Baker@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(96,	'Stanley',	NULL,	'Farmer',	'Stanley.Farmer@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(97,	'Leslie',	NULL,	'Christensen',	'Leslie.Christensen@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(98,	'Eddie',	NULL,	'Jefferson',	'Eddie.Jefferson@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');
INSERT INTO EMPLOYEE VALUES(99,	'Floyd',	NULL,	'Pearson',	'Floyd.Pearson@hamdard.edu',	1,	'ABC',	1,	'ABC',	123,	'ABC',	123,	1,	1,	SYSDATE(),	'ABC');

INSERT INTO COLLEGE VALUES(1,'East Bridge College');
INSERT INTO COLLEGE VALUES(2,'Ravenwood Conservatory');
INSERT INTO COLLEGE VALUES(3,'Timber Creek Grammar School');
INSERT INTO COLLEGE VALUES(4,'Woodside Elementary');
INSERT INTO COLLEGE VALUES(5,'Darwin High');
INSERT INTO COLLEGE VALUES(6,'Promise School for Girls');
INSERT INTO COLLEGE VALUES(7,'Sunnyside School for Girls');
INSERT INTO COLLEGE VALUES(8,'Summerville Middle School');
INSERT INTO COLLEGE VALUES(9,'Patriot School for Boys');
INSERT INTO COLLEGE VALUES(10,'Ocean View High School');

INSERT INTO DEPARTMENT VALUES(1,'Department of History');
INSERT INTO DEPARTMENT VALUES(2,'Department of Hospitality and Tourism Management');
INSERT INTO DEPARTMENT VALUES(3,'Department of International Studies');
INSERT INTO DEPARTMENT VALUES(4,'Department of Management and Marketing');
INSERT INTO DEPARTMENT VALUES(5,'Department of Mathematics');
INSERT INTO DEPARTMENT VALUES(6,'Department of Music');
INSERT INTO DEPARTMENT VALUES(7,'Department of Philosophy');
INSERT INTO DEPARTMENT VALUES(8,'Department of Physics and Astronomy');
INSERT INTO DEPARTMENT VALUES(9,'Department of Political Science');
INSERT INTO DEPARTMENT VALUES(10,'Department of Psychology');

INSERT INTO DESIGNATION VALUES(1,'C++ Professor');
INSERT INTO DESIGNATION VALUES(2,'Computer Information Systems Professor');
INSERT INTO DESIGNATION VALUES(3,'Computer Programming Professor');
INSERT INTO DESIGNATION VALUES(4,'Information Systems Professor');
INSERT INTO DESIGNATION VALUES(5,'Information Technology Professor');
INSERT INTO DESIGNATION VALUES(6,'IT Professor');
INSERT INTO DESIGNATION VALUES(7,'Java Programming Professor');


