INSERT INTO ROLEACCESS VALUES ('ROLE_READ', 'EMPLOYEE_READ');
INSERT INTO ROLEACCESS VALUES ('ROLE_READ', 'EMPLOYEE_SEARCH');
INSERT INTO ROLEACCESS VALUES ('ROLE_WRITE', 'EMPLOYEE_READ');
INSERT INTO ROLEACCESS VALUES ('ROLE_WRITE', 'EMPLOYEE_SEARCH');
INSERT INTO ROLEACCESS VALUES ('ROLE_WRITE', 'EMPLOYEE_UPDATE');
INSERT INTO ROLEACCESS VALUES ('ROLE_WRITE', 'EMPLOYEE_CREATE');
INSERT INTO ROLEACCESS VALUES ('ROLE_WRITE', 'EMPLOYEE_DELETE');

INSERT INTO EMPLOYEE VALUES (1, 'Jane', 'Doe', 25);
INSERT INTO EMPLOYEE VALUES (2, 'Jack', 'Doe', 30);
INSERT INTO EMPLOYEE VALUES (3, 'John', 'Smith', 44);
INSERT INTO EMPLOYEE VALUES (4, 'Jill', 'Smith', 23);
INSERT INTO EMPLOYEE VALUES (5, 'Jacob', 'Smith', 31);
