CREATE TABLE ROLEACCESS (
    ROLE VARCHAR(20),
    ACCESS VARCHAR(20)
);

CREATE TABLE EMPLOYEE (
    ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    AGE INTEGER
);

CREATE SEQUENCE EMP_ID START WITH 1 INCREMENT BY 1;
